### ISSUE TITLE
Not all required X509-SVID validations are taking place

### ISSUE THREAD

**Issue by dennisgove** [bloomberg/vault-auth-spire#10]
**Describe the bug**

Not all required [validations of X509 based SVIDs](https://github.com/spiffe/spiffe/blob/master/standards/X509-SVID.md#52-leaf-validation) are taking place. Specifically, the following are not happening:

- The certificate is a leaf certificate (I'm not 100% sure this check is occurring)
- CA field is set to false
- keyCertSign is not set
- cRLSign is not set

Per a conversation in the SPIFFE Slack workspace (#spire channel) the current thinking is that these validations should take place in the [`go-spiffe::VerifyPeerCertificate`](https://github.com/spiffe/go-spiffe/blob/master/spiffe/tls_verify.go#L39) method. Issue https://github.com/spiffe/go-spiffe/issues/25 has been created on that project to track the addition of those validations.

This ticket will ensure one of the following occurs:
1. Validations are added to `VerifyPeerCertificates` (https://github.com/spiffe/go-spiffe/issues/25) and our dependency is changed to require at least the version with those validations.
1. The validations are added to this project (perhaps as a stopgap while waiting for closure of https://github.com/spiffe/go-spiffe/issues/25).

**Comment by pawalt** [comment]
Resolved: https://github.com/spiffe/go-spiffe/issues/25
